version: '3'
services:
  web-client:
    build:
      context: ./apps/web-client
      dockerfile: Dockerfile
    image: s3-photos/web-client:prod
  photo-filter:
    build:
      context: ./apps/photo-filter
      dockerfile: Dockerfile
    image: s3-photos/photo-filter:prod
  photo-storage:
    build:
      context: ./apps/photo-storage
      dockerfile: Dockerfile
    image: s3-photos/photo-storage:prod
  s3-empty-bucket:
    build:
      context: ./apps/s3-empty-bucket
      dockerfile: Dockerfile
    image: s3-photos/s3-empty-bucket:prod
